### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by ccheek21** [newrelic/nri-postgresql#21]
##### Description of the problem
Error:
```time="2019-02-07T18:23:55Z" level=error msg="executing data source" data prefix=config/postgresql error="exit status 2" plugin name=sample_postgres stderr="panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x68f300]\n\ngoroutine 1 [running]:\ngithub.com/newrelic/nri-postgresql/src/metrics.PopulateMetrics(0x8d3520, 0xc42007f040, 0xc420065740, 0xc420058420, 0xc42007efa0, 0xc420058401)\n\t/data/jenkins/infra-integrations-nri-postgresql-release-linux-package-13/go/src/github.com/newrelic/nri-postgresql/src/metrics/metrics.go:41 +0x260\nmain.main()\n\t/data/jenkins/infra-integrations-nri-postgresql-release-linux-package-13/go/src/github.com/newrelic/nri-postgresql/src/postgresql.go:47 +0x63b\n"```

Config file: 
```integration_name: com.newrelic.postgresql

instances:
  # A name for the collection
  - name: sample_postgres
    # The only supported command is all_data
    command: all_data
    arguments:
      # The username for the postgres instance. Required.
      username: devops
      # The password for the postgres instance. Required.
      password: mypassword
      #password: Xp6TL8ZX8eYOKHQPcnPUqiZN5YOuKoszGNz48x1h
      # The hostname for the postgres instance. Defaults to localhost.
      hostname: 172.20.101.107
      # The port of the postgres instance. If PgBouncer is being used,
      # use the port it is running on. Defaults to 5432
      port: 31253
      #port: 31253
      # The JSON object which contains the entities to monitor. The nesting
      # levels of JSON are database name -> schema name -> table name -> index name
      # parameter is required for collection. If left as an empty JSON object nothing will be collected.
      # collection_list: '{"postgres":{"public":{"pg_table1":["pg_index1","pg_index2"],"pg_table2":[]}}}'
      collection_list: '{"keycloak":{"public":{"user_session":["constraint_57"],"protocol_mapper_config":["constraint_pmconfig"],"keycloak_role":["idx_keycloak_role_realm","idx_keycloak_role_client","UK_J3RWUVD56ONTGSUHOGM184WW2-2","constraint_a"],"client_scope_client":[],"composite_role":[],"authentication_execution":[]}}}'
      # collection_list: '{"keycloak":{"user_session":[],"realm":[],"keycloak_role":[],"client_session":[],"client":[],"authentication_execution":[]}}'
      #collection_list: '{"keycloak":{}}'
      # True if SSL is to be used. Defaults to false.
      enable_ssl: false
      # True if the SSL certificate should be trusted without validating.
      # Setting this to true may open up the monitoring service to MITM attacks.
      # Defaults to false.
      trust_server_certificate: true
      ssl_root_cert_location: /etc/newrelic-infra/root_cert.crt
      ssl_cert_location: /etc/newrelic-infra/postgresql.crt
      ssl_key_location: /etc/newrelic-infra/postgresql.key
      timeout:  10
      pgbouncer: true
    labels:
      env: k8sdev.fleetcomplete.co
      role: postgresql_cs-dev
  # A name for the collection
  - name: sample_postgres
    # The only supported command is all_data
    command: all_data
    arguments:
      # The username for the postgres instance. Required.
      username: devops
      # The password for the postgres instance. Required.
      password: mypassword
      # The hostname for the postgres instance. Defaults to localhost.
      hostname: 172.20.101.107
      # The port of the postgres instance. If PgBouncer is being used,
      # use the port it is running on. Defaults to 5432
      port: 31351
      #port: 31253
      # The JSON object which contains the entities to monitor. The nesting
      # levels of JSON are database name -> schema name -> table name -> index name
      # parameter is required for collection. If left as an empty JSON object nothing will be collected.
      # collection_list: '{"postgres":{"public":{"pg_table1":["pg_index1","pg_index2"],"pg_table2":[]}}}'
      collection_list: '{"keycloak":{}}'
      # True if SSL is to be used. Defaults to false.
      enable_ssl: false
      # True if the SSL certificate should be trusted without validating.
      # Setting this to true may open up the monitoring service to MITM attacks.
      # Defaults to false.
      trust_server_certificate: true
      ssl_root_cert_location: /etc/newrelic-infra/root_cert.crt
      ssl_cert_location: /etc/newrelic-infra/postgresql.crt
      ssl_key_location: /etc/newrelic-infra/postgresql.key
      timeout:  10
      pgbouncer: true
    labels:
      env: k8sdev.fleetcomplete.co
      role: postgresql_cs-stage```

##### OS

- [x] All of them
- [ ] Amazon Linux, all versions
- [ ] CentOS, version 6 or higher
- [ ] Debian, version 7 ("Wheezy") or higher
- [ ] Red Hat Enterprise Linux (RHEL), version 6 or higher
- [ ] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)
- [ ] Windows Server, 2008 and 2012 and their service packs

**Comment by sonaikar** [comment]
I tried to narrow down on the cause and I observed that "pgbouncer" is causing the trouble.

After disabling "pgbouncer" agent seems to be working.

pgbouncer: true # Comment out this line and nri-postgresql agent works.

Hope this helps to debug it further.

Thanks,
Sameer Sonaikar

**Comment by gashalot** [comment]
@sonaikar FYI, your issue may include a secret credential to your environment. If that is accurate, I'd suggest you rotate credentials immediately.

**Comment by sonaikar** [comment]
Thanks for notice. These passwords are dummy passwords.

**Comment by cpheps** [comment]
I blanked out all the password data in the ticket.
